title = "ByteCrash Blog"
baseURL = 'https://blog.bytecrash.xyz/'
languageCode = 'en'
defaultContentLanguage = "en"

# Enable emojis globally
enableEmoji = true

# Terminal theme
theme = "hugo-theme-terminal"
[pagination]
  pagerSize = 5

# Required for Chroma and the custom syntax highlighting
[markup.highlight]
  noClasses = false

[params]
  # dir name of your main content (default is `content/posts`)
  contentTypeName = "posts"
  
  # show selector to switch language
  showLanguageSelector = false
  
  # set theme to full screen width
  fullWidthTheme = false
  
  # center theme with default width
  centerTheme = false
  
  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically
  autoCover = true
  
  # set post to show the last updated
  showLastUpdated = false
  
  # whether to show a page's estimated reading time
  readingTime = false
  
  # whether to show a table of contents
  Toc = false
  
  # Set date/time format for posts
  dateFormat = "2006-01-02"

[languages]
  [languages.en]
    languageName = "English"
    title = "ByteCrash Blog"
    
    [languages.en.params]
      subtitle = "Technical insights, tutorials, and thoughts on software development"
      owner = "Chris"
      keywords = "programming, software development, tutorials"
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"
      
      [languages.en.params.logo]
        logoText = "ByteCrash"
        logoHomeLink = "/"
      
      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "posts"
          name = "Posts"
          url = "/posts"
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"